### ISSUE TITLE
update to 2022.2 failure

### ISSUE THREAD

**Issue by sashaid** [shamruk/hass-components-sha#3]
Aafter update to 2022.2.6

Configuration invalid

Platform error switch.kincony-sha - cannot import name 'SwitchDevice' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)

Please help.

**Comment by nordscan** [comment]
in /config/custom_components/kincony-sha/switch.py

change SwitchDevice to SwitchEntity  on line 10 and line 70

**Comment by sashaid** [comment]
Thank you for your email. I did this in february after 2 or 3 days of
debugging  . :-)

Say please if you can help me with inputs from Kincony KC868-Hx . Now your
project work just with OUTPUTS

I am new in python and have not idea how to make it to work. I think is not
possible from this project because the inputs work as one byte and not as
one bit like switches or lights. but in the same moment i can not read it
as an independent entity because it interferes with your code. Have you
some idea how to implement inputs within your code? It is possible or it is
a wrong way ?

The protocol is simple
Query the status of Inputs  SEND-> "RELAY-GET_INPUT-255" and feedback is
"RELAY-GET_INPUT-255,x,OK"  where " x is a Decimal Number The Maximum is
255(Binary is 11111111)"
I tried many codes to insert in your project but have problems when I try
to implement a new class :-(

Maybe you know more python and it is not so difficult for you to implement
INPUTS READ.
I appreciate any help from you or any suggestion.

Thank you in advance
